# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastro_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='valor',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='cadastro_pizza.Ingrediente', verbose_name='ingredientes'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sabor',
            field=models.CharField(max_length=100, unique=True, verbose_name='sabor'),
        ),
        migrations.AlterModelTable(
            name='ingrediente',
            table='ingredientes',
        ),
        migrations.AlterModelTable(
            name='pizza',
            table='pizzas',
        ),
    ]
